# Generated by Django 4.2.2 on 2023-06-24 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_1.category'),
        ),
        migrations.AlterField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(null=True),
        ),
    ]
